import { gs } from '@/utils/calculos'

const escapeHtml = (value) => String(value ?? '').replace(/[&<>'"]/g, character => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#39;', '"': '&quot;' }[character]))

export function printOrderReceipt(order) {
  const popup = window.open('', '_blank', 'noopener,noreferrer,width=420,height=720')
  if (!popup) return false
  const items = Array.isArray(order.items) ? order.items : []
  const payments = Array.isArray(order.payments) ? order.payments : order.pagos || []
  const paid = payments.filter(payment => payment.status === 'CONFIRMED' || payment.status === undefined).reduce((sum, payment) => sum + Number(payment.amountPyg ?? payment.monto ?? 0), 0)
  const when = order.createdAt || order.creadoEn || order.fecha
  const tracking = order.publicToken && import.meta.env.VITE_API_URL ? `${String(import.meta.env.VITE_API_URL).replace(/\/$/, '')}/api/orders/public/${encodeURIComponent(order.publicToken)}` : ''
  popup.document.write(`<!doctype html><html lang="es"><head><meta charset="utf-8"><title>Comprobante ${escapeHtml(order.orderNumber || order.codigo || '')}</title><style>body{font:13px system-ui,sans-serif;margin:18px;color:#111}h1{font-size:20px;margin:0 0 4px}.muted{color:#555}.row{display:flex;justify-content:space-between;gap:12px;margin:8px 0}.items{margin:18px 0;border-top:1px dashed #999}.item{padding:9px 0;border-bottom:1px dashed #999}.total{font-size:17px;font-weight:700}.small{font-size:11px;word-break:break-all}@media print{body{margin:8px}}</style></head><body><h1>Comprobante de compra</h1><p class="muted">${escapeHtml(order.orderNumber || order.codigo || 'Pedido')} · ${escapeHtml(when ? new Date(when).toLocaleString('es-PY') : '')}</p><p><strong>Cliente:</strong> ${escapeHtml(order.customer?.name || order.cliente || 'Consumidor final')}</p><div class="items">${items.map(item => `<div class="item"><strong>${escapeHtml(item.description || item.nombre || 'Producto')}</strong><div class="row"><span>${escapeHtml(item.quantity || 1)} × ${escapeHtml(gs(item.unitPricePyg ?? item.precio ?? 0))}</span><span>${escapeHtml(gs(item.totalPyg ?? (item.quantity || 1) * (item.unitPricePyg ?? item.precio ?? 0)))}</span></div></div>`).join('')}</div><div class="row"><span>Subtotal</span><span>${escapeHtml(gs(order.subtotalPyg ?? order.subtotal ?? order.totalPyg ?? order.total ?? 0))}</span></div>${Number(order.discountPyg || order.descuento || 0) ? `<div class="row"><span>Descuento</span><span>− ${escapeHtml(gs(order.discountPyg || order.descuento))}</span></div>` : ''}${Number(order.deliveryPyg || order.montoDelivery || 0) ? `<div class="row"><span>Entrega</span><span>${escapeHtml(gs(order.deliveryPyg || order.montoDelivery))}</span></div>` : ''}<div class="row total"><span>Total</span><span>${escapeHtml(gs(order.totalPyg ?? order.total ?? 0))}</span></div><div class="row"><span>Pagado</span><span>${escapeHtml(gs(paid || order.totalPagado || 0))}</span></div><p class="muted">Entrega: ${escapeHtml(order.fulfillmentStatus || order.deliveryType || order.entrega || 'En preparación')}</p>${tracking ? `<p class="small">Seguimiento: ${escapeHtml(tracking)}</p>` : ''}<script>window.onload=()=>window.print()<\/script></body></html>`)
  popup.document.close()
  return true
}
