import assert from 'node:assert/strict'
const [base, admin, seller, company] = process.argv.slice(2)
if (!base || !admin || !seller || !company) throw new Error('base admin seller company requeridos')
let checks = 0
async function req(path, token, method = 'GET', body, expected = 200) {
  const response = await fetch(base + path, { method, headers: { Authorization: `Bearer ${token}`, 'Content-Type': 'application/json' }, ...(body ? { body: JSON.stringify(body) } : {}) })
  const data = await response.json()
  assert.equal(response.status, expected, `${method} ${path}: ${JSON.stringify(data)}`)
  checks++; return data
}
await req('/api/payment-accounts', company, 'GET', null, 401)
await req('/api/payment-accounts', seller, 'POST', { name: 'Forbidden' }, 403)
const usd = await req('/api/payment-accounts', admin, 'POST', { name: 'Banco prueba USD', kind: 'TRANSFER', currency: 'USD', bank: 'Banco sintético', holder: 'Empresa prueba', accountNumber: 'TEST-USD-01' }, 201)
const trade = await req('/api/payment-accounts', admin, 'POST', { name: 'Equipo como parte de pago', kind: 'TRADE_IN', currency: 'PYG' }, 201)
assert.ok((await req('/api/payment-accounts', seller)).some(a => a.id === usd.id))
const p = await req('/api/products', admin, 'POST', { name: 'Equipo nuevo prueba', sku: `ACCOUNTS-${Date.now()}`, pricePyg: 1000000, stock: 5 }, 201)
const order = await req('/api/orders', seller, 'POST', { items: [{ productId: p.id, description: p.name, quantity: 1, unitPricePyg: 1000000 }], payments: [{ accountId: usd.id, originalAmount: '10.50', exchangeRatePyg: '7500', amountPyg: 78750, method: 'TRANSFER', status: 'CONFIRMED' }] }, 201)
assert.equal(order.payments[0].amountPyg, 78750)
assert.equal(order.payments[0].currency, 'USD')
assert.equal(Number(order.payments[0].originalAmount), 10.5)
const snapshot = JSON.stringify(order.payments[0].accountSnapshot)
await req('/api/payment-accounts', admin, 'PATCH', { id: usd.id, name: 'Nombre cambiado', accountNumber: 'TEST-CHANGED', isActive: false })
const historical = (await req('/api/orders', seller)).find(o => o.id === order.id)
assert.equal(JSON.stringify(historical.payments[0].accountSnapshot), snapshot)
assert.ok(!(await req('/api/payment-accounts', seller)).some(a => a.id === usd.id))
const serial = `TEST-IMEI-${Date.now()}`
const payment = await req('/api/payments', seller, 'POST', { orderId: order.id, accountId: trade.id, method: 'TRADE_IN', originalAmount: 100000, exchangeRatePyg: 1, amountPyg: 100000, status: 'CONFIRMED', tradeIn: { serial, model: 'Teléfono de prueba', conditionNotes: 'Revisar pantalla' } }, 201)
await req('/api/trade-ins', seller, 'GET', null, 403)
const device = (await req('/api/trade-ins', admin)).find(d => d.serial === serial)
assert.ok(device); assert.equal(device.paymentId, payment.id); assert.equal(device.orderId, order.id)
assert.equal(device.status, 'RECEIVED'); assert.ok(!device.productId)
assert.ok(!(await req('/api/products', admin)).some(item => item.imei === serial))
for (const status of ['REVIEW', 'REPAIR', 'READY']) await req('/api/trade-ins', admin, 'PATCH', { id: device.id, status, notes: 'Prueba de seguimiento', ...(status === 'REPAIR' ? { repairCostPyg: 25000 } : {}) })
const stocked = await req('/api/trade-ins', admin, 'PATCH', { id: device.id, status: 'STOCK', destination: 'OFFER', pricePyg: 200000, notes: 'Oferta aprobada' })
assert.ok(stocked.productId)
const products = await req('/api/products', admin)
assert.equal(products.find(item => item.id === stocked.productId)?.stock, 1)
await req('/api/trade-ins', admin, 'PATCH', { id: device.id, status: 'STOCK', destination: 'OFFER', pricePyg: 200000 }, 409)
assert.equal((await req('/api/products', admin)).filter(item => item.imei === serial).length, 1)
console.log(`Cuentas, cotización congelada, privacidad y trazabilidad de Trade-In: ${checks} comprobaciones OK`)
