// Ejecuta pruebas TypeScript con las dependencias ya instaladas del backend.
const ts = require('typescript')
const fs = require('node:fs')
require.extensions['.ts'] = (module, path) => module._compile(ts.transpileModule(fs.readFileSync(path, 'utf8'), {
  compilerOptions: { esModuleInterop: true, module: ts.ModuleKind.CommonJS, target: ts.ScriptTarget.ES2022 },
}).outputText, path)
require('./consistency.test.ts')
require('./cookie-secure.test.ts')
require('./email-template.test.ts')
require('./attachment-storage.test.ts')
require('./payment-proofs.test.ts')
require('./aex-webhook.test.ts')
require('./aex-label.test.ts')
require('./aex-ship-route.test.ts')
require('./presence.test.ts')
require('./pricing.test.ts')
require('./print-metrics.test.ts')
require('./price-lists.test.ts')
require('./receipt-snapshot.test.ts')
require('./service-number.test.ts')
require('./secret-crypto.test.ts')
require('./sku.test.ts')
require('./menciones.test.ts')
require('./product-import.test.ts')
require('./kardex.test.ts')
require('./costs.test.ts')
require('./inspection.test.ts')
require('./product-search.test.ts')
require('./imeicheck.test.ts')
require('./print-bridge.test.ts')
require('./user-invitations.test.ts')
require('./delivery.test.ts')
require('./collections.test.ts')
require('./segments.test.ts')
require('./audit-labels.test.ts')
require('./insurance.test.ts')
require('./pin.test.ts')
require('./errors-quota.test.ts')
require('./sifen-cdc.test.ts')
require('./sifen-config.test.ts')
require('./sifen-mapping.test.ts')
require('./sifen-xml.test.ts')
require('./sifen-client.test.ts')
require('./finance-insurance.test.ts')
require('./reconciliation.test.ts')
require('./reporting-margen.test.ts')
require('./public-token.test.ts')
require('./device-report.test.ts')
require('./service-order.test.ts')
// Al final: este test comparte proceso con aex-label, que borra claves para
// probar el camino sin configuración.
require('./aex-ship.test.ts')
