import { useMemo, useState } from 'react'
import { ArrowLeft, Check, ChevronRight, CreditCard, LayoutDashboard, Package, Plus, Search, ShoppingCart, UserRound, WalletCards } from 'lucide-react'

const products = [
  { id: 1, name: 'iPhone 15 Pro 256 GB', variant: 'Titanio natural · Nuevo', price: 6850000, stock: 3, icon: '📱' },
  { id: 2, name: 'Funda MagSafe Armor', variant: 'Transparente · iPhone 15 Pro', price: 180000, stock: 12, icon: '🧩' },
  { id: 3, name: 'Cargador USB-C 20W', variant: 'Apple · Original', price: 320000, stock: 8, icon: '🔌' },
  { id: 4, name: 'AirPods Pro 2', variant: 'USB-C · Nuevo', price: 1850000, stock: 2, icon: '🎧' },
]
const money = (n) => `Gs. ${new Intl.NumberFormat('es-PY').format(n)}`

export default function Demo() {
  const [view, setView] = useState('inicio')
  const [query, setQuery] = useState('')
  const [cart, setCart] = useState([])
  const [payment, setPayment] = useState('Efectivo')
  const [pin, setPin] = useState('')
  const [pinVerified, setPinVerified] = useState(false)
  const filtered = products.filter((p) => `${p.name} ${p.variant}`.toLowerCase().includes(query.toLowerCase()))
  const total = useMemo(() => cart.reduce((sum, p) => sum + p.price, 0), [cart])
  const add = (p) => { setCart((items) => items.some((x) => x.id === p.id) ? items : [...items, p]); setView('venta') }

  if (!pinVerified) return <div className="grid min-h-dvh place-items-center bg-[#071018] p-5 text-white"><div className="w-full max-w-sm rounded-3xl border border-white/10 bg-[#0b1822] p-7 text-center"><img src="/logo-dark.svg" alt="MobOS" className="mx-auto h-10 w-auto"/><p className="mt-8 text-xs font-bold uppercase tracking-[.2em] text-[#15D7B8]">Demo segura</p><h1 className="mt-3 text-2xl font-bold">Ingresá con tu PIN</h1><p className="mt-2 text-sm text-slate-400">PIN demo: 2001</p><input autoFocus value={pin} onChange={(e) => setPin(e.target.value.replace(/\D/g, '').slice(0, 4))} inputMode="numeric" maxLength={4} className="mt-6 w-full rounded-xl border border-white/10 bg-white/5 px-4 py-4 text-center text-2xl tracking-[.5em] outline-none focus:border-[#15D7B8]"/><button onClick={() => pin === '2001' && setPinVerified(true)} className="mt-4 w-full rounded-xl bg-[#15D7B8] px-4 py-3 font-bold text-[#071018]">Abrir POS demo</button><a href="https://controlaria.online" className="mt-5 block text-xs text-slate-500">Volver a la landing</a></div></div>
  return <div className="min-h-dvh bg-[#071018] text-white">
    <header className="border-b border-white/10 bg-[#071018]/95 px-5 py-4"><div className="mx-auto flex max-w-6xl items-center justify-between"><a href="https://controlaria.online"><img src="/logo-dark.svg" alt="MobOS" className="h-9 w-auto" /></a><div className="flex items-center gap-3 text-xs text-slate-400"><span className="hidden sm:inline">Demo interactiva</span><a href="https://app.controlaria.online/login" className="rounded-lg border border-white/15 px-3 py-2 font-semibold text-white">Entrar al sistema</a></div></div></header>
    <main className="mx-auto max-w-6xl px-4 py-7 sm:px-6"><div className="mb-6 flex flex-wrap items-center justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[.2em] text-[#15D7B8]">MobOS 0.2 · Demo</p><h1 className="mt-2 text-3xl font-bold tracking-tight sm:text-4xl">Probá una venta completa</h1><p className="mt-2 text-sm text-slate-400">Nada de lo que hagas modifica una tienda real.</p></div><a href="https://controlaria.online" className="inline-flex items-center gap-2 text-sm font-semibold text-[#15D7B8]"><ArrowLeft size={16}/> Volver</a></div>
      <div className="grid gap-5 lg:grid-cols-[190px_1fr]"><aside className="rounded-2xl border border-white/10 bg-[#0b1822] p-3"><div className="mb-4 flex items-center gap-2 rounded-xl bg-[#15D7B8]/10 p-3 text-xs font-bold text-[#15D7B8]"><span className="grid h-7 w-7 place-items-center rounded-lg bg-[#15D7B8] text-[#071018]">D</span>Dario · Vendedor</div>{[['inicio', LayoutDashboard, 'Resumen'], ['venta', ShoppingCart, 'Cargar venta'], ['stock', Package, 'Stock']].map(([key, Icon, label]) => <button key={key} onClick={() => setView(key)} className={`mb-1 flex w-full items-center gap-3 rounded-xl px-3 py-3 text-left text-sm ${view === key ? 'bg-white/10 text-white' : 'text-slate-400 hover:bg-white/5'}`}><Icon size={17}/>{label}</button>)}</aside>
        <section className="min-w-0 rounded-2xl border border-white/10 bg-[#0b1822] p-4 sm:p-6">
          {view === 'inicio' && <><p className="text-sm text-slate-400">Buenos días, Dario</p><h2 className="mt-1 text-2xl font-bold">Centro de control</h2><div className="mt-6 grid gap-3 sm:grid-cols-3">{[['Ventas de hoy', 'Gs. 12.840.500', '+18,4%', WalletCards], ['Margen real', '27,4%', 'Saludable', LayoutDashboard], ['Stock crítico', '4 alertas', 'Revisar ahora', Package]].map(([label, value, detail, Icon]) => <div key={label} className="rounded-2xl border border-white/10 bg-white/[.035] p-4"><Icon size={18} className="text-[#15D7B8]"/><p className="mt-5 text-xs text-slate-500">{label}</p><b className="mt-1 block text-xl">{value}</b><span className="text-xs text-[#15D7B8]">{detail}</span></div>)}</div><button onClick={() => setView('venta')} className="mt-5 flex w-full items-center justify-between rounded-xl bg-[#15D7B8] px-4 py-4 text-left font-bold text-[#071018]">Crear una venta de prueba <ChevronRight size={19}/></button></>}
          {view === 'venta' && <><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[.16em] text-[#15D7B8]">Paso 1 · POS</p><h2 className="mt-2 text-2xl font-bold">Cargar venta</h2></div><span className="rounded-lg border border-white/10 px-3 py-2 text-xs text-slate-400">Vendedor: Dario</span></div><div className="mt-6 grid gap-5 xl:grid-cols-[1fr_290px]"><div><label className="relative block"><Search className="absolute left-3 top-3 text-slate-500" size={17}/><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Buscar producto, modelo o SKU..." className="w-full rounded-xl border border-white/10 bg-white/5 py-3 pl-10 pr-4 text-sm outline-none focus:border-[#15D7B8]" /></label><div className="mt-4 grid gap-3 sm:grid-cols-2">{filtered.map((p) => <button key={p.id} onClick={() => add(p)} className="flex items-center gap-3 rounded-2xl border border-white/10 bg-white/[.035] p-3 text-left transition hover:border-[#15D7B8]/60"><span className="grid h-12 w-12 place-items-center rounded-xl bg-[#123c42] text-2xl">{p.icon}</span><span className="min-w-0 flex-1"><b className="block truncate text-sm">{p.name}</b><small className="mt-1 block truncate text-xs text-slate-500">{p.variant}</small><strong className="mt-2 block text-sm text-[#15D7B8]">{money(p.price)}</strong></span><Plus size={17} className="text-slate-500"/></button>)}</div></div><div className="rounded-2xl border border-white/10 bg-[#071018] p-4"><div className="flex items-center gap-2 border-b border-white/10 pb-3"><UserRound size={17} className="text-[#15D7B8]"/><b className="text-sm">Cliente</b></div><p className="mt-3 rounded-lg border border-white/10 bg-white/5 px-3 py-2.5 text-sm">María González</p><p className="mt-2 text-xs text-[#15D7B8]">✓ Cliente encontrado · 4 compras</p><div className="mt-5 border-t border-white/10 pt-4"><b className="text-sm">Carrito · {cart.length} productos</b>{cart.map((p) => <div key={p.id} className="mt-3 flex justify-between gap-2 text-xs"><span className="truncate text-slate-300">{p.name}</span><span>{money(p.price)}</span></div>)}{cart.length > 0 && <><div className="mt-4 flex justify-between border-t border-white/10 pt-3 font-bold"><span>Total</span><span className="text-[#15D7B8]">{money(total)}</span></div><button onClick={() => setView('pago')} className="mt-4 w-full rounded-xl bg-[#15D7B8] px-4 py-3 text-sm font-bold text-[#071018]">Continuar al pago</button></>}</div></div></div></>}
          {view === 'pago' && <div className="mx-auto max-w-xl"><p className="text-xs font-bold uppercase tracking-[.16em] text-[#15D7B8]">Paso 2 · Cobro</p><h2 className="mt-2 text-2xl font-bold">Elegí cómo paga el cliente</h2><div className="mt-6 rounded-2xl border border-white/10 bg-white/[.035] p-5"><div className="flex items-center justify-between"><span className="text-sm text-slate-400">Total de la venta</span><strong className="text-2xl text-[#15D7B8]">{money(total)}</strong></div><div className="mt-6 grid grid-cols-2 gap-3 sm:grid-cols-4">{['Efectivo', 'Transferencia', 'POS', 'USDT'].map((method) => <button key={method} onClick={() => setPayment(method)} className={`rounded-xl border px-3 py-4 text-xs font-bold ${payment === method ? 'border-[#15D7B8] bg-[#15D7B8]/10 text-[#15D7B8]' : 'border-white/10 text-slate-400'}`}><CreditCard className="mx-auto mb-2" size={18}/>{method}</button>)}</div><div className="mt-5 rounded-xl border border-amber-300/20 bg-amber-300/5 p-3 text-xs text-amber-200">También podés dividir este cobro o dejar un saldo pendiente.</div><button onClick={() => setView('confirmado')} className="mt-5 flex w-full items-center justify-center gap-2 rounded-xl bg-[#15D7B8] px-4 py-3 font-bold text-[#071018]">Confirmar venta · {payment} <Check size={18}/></button></div></div>}
          {view === 'confirmado' && <div className="mx-auto max-w-xl text-center"><div className="mx-auto grid h-16 w-16 place-items-center rounded-full bg-[#15D7B8] text-[#071018]"><Check size={31}/></div><p className="mt-6 text-xs font-bold uppercase tracking-[.16em] text-[#15D7B8]">Venta registrada</p><h2 className="mt-2 text-3xl font-bold">Todo quedó conectado.</h2><p className="mx-auto mt-4 max-w-md text-sm leading-6 text-slate-400">Stock descontado, caja actualizada, comisión vinculada y cliente listo para la garantía.</p><div className="mt-7 grid gap-3 text-left sm:grid-cols-3">{[['Venta', money(total)], ['Medio', payment], ['Cliente', 'María González']].map(([label, value]) => <div key={label} className="rounded-xl border border-white/10 bg-white/[.035] p-4"><span className="text-xs text-slate-500">{label}</span><b className="mt-2 block truncate text-sm">{value}</b></div>)}</div><button onClick={() => { setCart([]); setView('venta') }} className="mt-7 rounded-xl bg-[#15D7B8] px-5 py-3 text-sm font-bold text-[#071018]">Cargar otra venta</button></div>}
          {view === 'stock' && <><p className="text-xs font-bold uppercase tracking-[.16em] text-[#15D7B8]">Inventario</p><h2 className="mt-2 text-2xl font-bold">Stock de la tienda</h2><div className="mt-6 space-y-3">{products.map((p) => <div key={p.id} className="flex items-center gap-3 rounded-2xl border border-white/10 bg-white/[.035] p-4"><span className="grid h-11 w-11 place-items-center rounded-xl bg-[#123c42] text-xl">{p.icon}</span><div className="min-w-0 flex-1"><b className="block truncate text-sm">{p.name}</b><span className="text-xs text-slate-500">{p.variant}</span></div><span className={`rounded-full px-3 py-1 text-xs font-bold ${p.stock <= 3 ? 'bg-amber-300/10 text-amber-200' : 'bg-[#15D7B8]/10 text-[#15D7B8]'}`}>{p.stock} unidades</span></div>)}</div></>}
        </section></div>
    </main>
  </div>
}
