import { ArrowRight, BarChart3, Check, CreditCard, Package, ShieldCheck, Smartphone, Users } from 'lucide-react'

const features = [
  ['POS móvil', 'Vende desde cualquier sucursal con acceso rápido por PIN.', Smartphone],
  ['Inventario inteligente', 'Variantes, IMEI, seriales, fotos y stock en un solo lugar.', Package],
  ['Pagos sin límites', 'Efectivo, transferencia, POS, USDT y pagos parciales.', CreditCard],
  ['Equipo conectado', 'Vendedores, permisos, comisiones y rendimiento automático.', Users],
  ['Control total', 'Reportes, garantías y trazabilidad para decidir mejor.', ShieldCheck],
  ['Resultados claros', 'Ventas, caja, margen y faltantes visibles cada día.', BarChart3],
]

export default function Landing() {
  return <div className="min-h-dvh bg-[#071018] text-white">
    <header className="mx-auto flex max-w-6xl items-center justify-between px-5 py-5"><a href="#inicio" className="flex items-center gap-2 text-lg font-bold tracking-tight"><span className="grid h-8 w-8 place-items-center rounded-xl bg-[#16d7b8] text-[#071018]">M</span>Controlaria</a><nav className="hidden items-center gap-7 text-sm text-slate-400 md:flex"><a href="#funciones">Funciones</a><a href="#precio">Precio</a><a className="rounded-xl bg-[#123344] px-4 py-2 text-white" href="https://app.controlaria.online">Entrar a MobOS <ArrowRight className="ml-1 inline" size={15}/></a></nav></header>
    <main>
      <section id="inicio" className="mx-auto grid max-w-6xl gap-12 px-5 pb-24 pt-20 md:grid-cols-[1.05fr_.95fr] md:items-center md:pt-32"><div><p className="text-xs font-bold uppercase tracking-[.2em] text-[#16d7b8]">El sistema operativo para tu tienda</p><h1 className="mt-5 text-6xl font-bold leading-[.98] tracking-[-.06em] md:text-8xl">Vende más.<br/><span className="text-[#16d7b8]">Controla todo.</span></h1><p className="mt-7 max-w-xl text-lg leading-8 text-slate-400">MobOS reúne ventas, inventario, pagos y equipo en una experiencia rápida, clara y hecha para negocios móviles.</p><div className="mt-9 flex flex-wrap items-center gap-5"><a href="https://app.controlaria.online" className="inline-flex items-center gap-2 rounded-xl bg-[#16d7b8] px-5 py-3 font-bold text-[#071018]">Probar MobOS <ArrowRight size={18}/></a><a href="#funciones" className="text-sm font-semibold">Ver funciones <ArrowRight className="ml-1 inline" size={15}/></a></div><div className="mt-8 flex flex-wrap gap-4 text-xs text-slate-500"><span><Check className="mr-1 inline text-[#16d7b8]" size={14}/> Sin contratos</span><span><Check className="mr-1 inline text-[#16d7b8]" size={14}/> Multiempresa</span><span><Check className="mr-1 inline text-[#16d7b8]" size={14}/> Soporte incluido</span></div></div><div className="rounded-3xl border border-[#2d5364] bg-gradient-to-br from-[#183747] to-[#0d1d28] p-6 shadow-2xl"><div className="flex items-center gap-2 text-xs text-slate-400"><span className="h-2 w-2 rounded-full bg-[#16d7b8]"/> Resumen del día <span className="ml-auto text-[10px] text-[#16d7b8]">● EN VIVO</span></div><div className="mt-12 border-b border-white/10 pb-6"><span className="text-xs text-slate-400">Ventas de hoy</span><strong className="mt-2 block text-4xl tracking-tight">Gs. 12.840.500</strong><span className="text-xs text-[#16d7b8]">↗ 18,4%</span></div><div className="grid grid-cols-3 gap-3 py-6 text-xs"><div><span className="text-slate-500">Órdenes</span><b className="mt-1 block text-base">38</b></div><div><span className="text-slate-500">Ticket promedio</span><b className="mt-1 block text-base">Gs. 337.908</b></div><div><span className="text-slate-500">Stock crítico</span><b className="mt-1 block text-base text-amber-300">4 productos</b></div></div><div className="flex h-20 items-end gap-3">{[35,54,43,76,62,92,70].map((h,i)=><i key={i} style={{height:`${h}%`}} className="flex-1 rounded-t bg-gradient-to-t from-[#167b83] to-[#16d7b8]"/>)}</div></div></section>
      <section id="funciones" className="border-y border-white/10"><div className="mx-auto max-w-6xl px-5 py-24"><p className="text-xs font-bold uppercase tracking-[.2em] text-[#16d7b8]">Todo en un solo lugar</p><div className="mt-4 flex flex-wrap items-end justify-between gap-6"><h2 className="text-4xl font-bold tracking-tight md:text-5xl">La operación completa,<br/><span className="text-[#16d7b8]">sin complicaciones.</span></h2><p className="max-w-xs text-sm leading-6 text-slate-400">Menos planillas. Menos errores. Más claridad para crecer todos los días.</p></div><div className="mt-14 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{features.map(([title,text,Icon])=><article key={title} className="rounded-2xl border border-white/10 bg-[#0c1a24] p-6"><div className="grid h-11 w-11 place-items-center rounded-xl bg-[#123c42] text-[#16d7b8]"><Icon size={21}/></div><h3 className="mt-6 font-semibold">{title}</h3><p className="mt-2 text-sm leading-6 text-slate-400">{text}</p></article>)}</div></div></section>
      <section id="precio" className="mx-auto max-w-6xl px-5 py-24"><div className="flex flex-col justify-between gap-10 rounded-3xl bg-gradient-to-br from-[#115c5a] to-[#16d7b8] p-8 text-[#071018] md:flex-row md:items-center md:p-16"><div><p className="text-xs font-bold uppercase tracking-[.2em] text-teal-100">Un plan. Todo incluido.</p><h2 className="mt-4 text-4xl font-bold tracking-tight md:text-5xl">Tu negocio merece<br/>mejor control.</h2><p className="mt-4 max-w-md text-sm leading-6 text-teal-50">Todas las herramientas para vender, administrar y crecer, sin contratos ni sorpresas.</p></div><div className="min-w-[230px]"><div><span className="text-sm font-bold">USD </span><strong className="text-8xl font-bold tracking-[-.08em]">10</strong><span className="text-sm"> / mes</span></div><a href="https://app.controlaria.online" className="mt-5 flex items-center justify-center gap-2 rounded-xl bg-[#071018] px-5 py-3 font-bold text-white">Empezar ahora <ArrowRight size={18}/></a><p className="mt-3 text-center text-xs text-teal-50">Sin permanencia · Soporte incluido</p></div></div></section>
    </main><footer className="mx-auto flex max-w-6xl flex-wrap justify-between gap-4 border-t border-white/10 px-5 py-8 text-xs text-slate-500"><span className="font-semibold text-white">Controlaria · MobOS</span><span>Gestión inteligente para tiendas móviles</span><span>© 2026 OwnCoding</span></footer>
  </div>
}
