import { ArrowRight, BarChart3, Check, ChevronRight, CreditCard, Globe2, Package, Receipt, ShieldCheck, Smartphone, Users, Wrench } from 'lucide-react'

const modules = [
  ['Inicio', 'Ventas, ganancia bruta, caja, faltantes y pendientes.', BarChart3],
  ['Ventas y POS', 'Cobros, descuentos, reservas, combos, cambios y devoluciones.', Receipt],
  ['Productos y compatibilidad', 'Modelos, colores, capacidades, estados y accesorios compatibles.', Smartphone],
  ['Stock', 'Existencias por local, reservas, tránsito, transferencias y ajustes.', Package],
  ['Compras e importaciones', 'Proveedores, pedidos, costos finales y reposición.', Globe2],
  ['Caja y gastos', 'Cierres diarios, cuentas, comisiones y medios de pago.', CreditCard],
  ['Clientes', 'Historial, RUC/CI, equipos asociados y seguimiento.', Users],
  ['Garantías y servicio', 'IMEI, seriales, reparaciones, plazos y resolución.', Wrench],
  ['Reportes y controles', 'Resultados por producto, categoría y vendedor.', ShieldCheck],
]
const checks = ['Acceso por PIN para cada vendedor', 'Comisiones y rendimiento automáticos', 'Multiempresa, multisucursal y multidivisa', 'PYG, USD, BRL, EUR, USDT y pagos combinados', 'Clientes por nombre, teléfono, email, RUC o CI', 'Variantes: color, capacidad, estado y más', 'Delivery, encomienda, retiro y pagos pendientes', 'Exportaciones, garantías, trazabilidad y permisos']

export default function Landing() {
  return <div className="min-h-dvh bg-[#071018] text-white">
    <header className="sticky top-0 z-20 border-b border-white/10 bg-[#071018]/90 backdrop-blur"><div className="mx-auto flex max-w-6xl items-center justify-between px-5 py-4"><a href="#inicio" className="flex items-center gap-3"><img src="/logo.svg" alt="MobOS" className="h-10 w-auto rounded-xl"/><span className="hidden text-sm font-semibold text-slate-300 sm:block">Controlaria</span></a><nav className="hidden items-center gap-7 text-sm text-slate-400 md:flex"><a href="#modulos">Módulos</a><a href="#flujo">Cómo funciona</a><a href="#precio">Precio</a><a className="rounded-xl bg-[#123344] px-4 py-2 text-white" href="https://app.controlaria.online">Entrar a MobOS <ArrowRight className="ml-1 inline" size={15}/></a></nav></div></header>
    <main>
      <section id="inicio" className="mx-auto grid max-w-6xl gap-12 px-5 pb-28 pt-20 md:grid-cols-[1.05fr_.95fr] md:items-center md:pt-32"><div><p className="text-xs font-bold uppercase tracking-[.2em] text-[#16d7b8]">El sistema operativo para tu tienda</p><h1 className="mt-5 text-6xl font-bold leading-[.98] tracking-[-.06em] md:text-8xl">Vende más.<br/><span className="text-[#16d7b8]">Controla todo.</span></h1><p className="mt-7 max-w-xl text-lg leading-8 text-slate-400">MobOS conecta ventas, inventario, pagos, clientes y equipo en una experiencia rápida, clara y diseñada para negocios móviles.</p><div className="mt-9 flex flex-wrap items-center gap-5"><a href="https://app.controlaria.online" className="inline-flex items-center gap-2 rounded-xl bg-[#16d7b8] px-5 py-3 font-bold text-[#071018]">Probar MobOS <ArrowRight size={18}/></a><a href="#modulos" className="text-sm font-semibold">Explorar todo <ArrowRight className="ml-1 inline" size={15}/></a></div><div className="mt-8 flex flex-wrap gap-4 text-xs text-slate-500"><span><Check className="mr-1 inline text-[#16d7b8]" size={14}/> Sin contratos</span><span><Check className="mr-1 inline text-[#16d7b8]" size={14}/> Todo incluido</span><span><Check className="mr-1 inline text-[#16d7b8]" size={14}/> Soporte incluido</span></div></div><div className="rounded-3xl border border-[#2d5364] bg-gradient-to-br from-[#183747] to-[#0d1d28] p-6 shadow-2xl"><div className="flex items-center gap-2 text-xs text-slate-400"><span className="h-2 w-2 rounded-full bg-[#16d7b8]"/> Resumen del día <span className="ml-auto text-[10px] text-[#16d7b8]">● EN VIVO</span></div><div className="mt-12 border-b border-white/10 pb-6"><span className="text-xs text-slate-400">Ventas de hoy</span><strong className="mt-2 block text-4xl tracking-tight">Gs. 12.840.500</strong><span className="text-xs text-[#16d7b8]">↗ 18,4%</span></div><div className="grid grid-cols-3 gap-3 py-6 text-xs"><div><span className="text-slate-500">Órdenes</span><b className="mt-1 block text-base">38</b></div><div><span className="text-slate-500">Ticket promedio</span><b className="mt-1 block text-base">Gs. 337.908</b></div><div><span className="text-slate-500">Stock crítico</span><b className="mt-1 block text-base text-amber-300">4 productos</b></div></div><div className="flex h-20 items-end gap-3">{[35,54,43,76,62,92,70].map((h,i)=><i key={i} style={{height:`${h}%`}} className="flex-1 rounded-t bg-gradient-to-t from-[#167b83] to-[#16d7b8]"/>)}</div></div></section>
      <section id="modulos" className="border-y border-white/10"><div className="mx-auto max-w-6xl px-5 py-24"><p className="text-xs font-bold uppercase tracking-[.2em] text-[#16d7b8]">Nueve áreas conectadas</p><div className="mt-4 flex flex-wrap items-end justify-between gap-6"><h2 className="text-4xl font-bold tracking-tight md:text-5xl">Toda tu operación,<br/><span className="text-[#16d7b8]">en una sola vista.</span></h2><p className="max-w-sm text-sm leading-6 text-slate-400">Cada módulo comparte los mismos datos. Una venta actualiza stock, caja, cliente, vendedor y garantía.</p></div><div className="mt-14 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{modules.map(([title,text,Icon])=><article key={title} className="rounded-2xl border border-white/10 bg-[#0c1a24] p-6 transition hover:-translate-y-1 hover:border-[#16d7b855]"><div className="grid h-11 w-11 place-items-center rounded-xl bg-[#123c42] text-[#16d7b8]"><Icon size={21}/></div><h3 className="mt-6 font-semibold">{title}</h3><p className="mt-2 text-sm leading-6 text-slate-400">{text}</p><a href="#precio" className="mt-5 inline-flex items-center text-xs font-bold text-[#16d7b8]">Incluido <ChevronRight size={15}/></a></article>)}</div></div></section>
      <section id="flujo" className="mx-auto grid max-w-6xl gap-14 px-5 py-28 md:grid-cols-2 md:items-center"><div><p className="text-xs font-bold uppercase tracking-[.2em] text-[#16d7b8]">Una venta conecta todo</p><h2 className="mt-4 text-4xl font-bold tracking-tight md:text-5xl">Del primer toque<br/><span className="text-[#16d7b8]">al control total.</span></h2><p className="mt-6 max-w-xl text-base leading-7 text-slate-400">El vendedor entra con su PIN, busca al cliente, encuentra el producto y recibe sugerencias de compatibilidad. MobOS registra el cobro, descuenta el stock, calcula la comisión y deja lista la garantía.</p><a href="https://app.controlaria.online" className="mt-8 inline-flex items-center gap-2 text-sm font-bold text-[#16d7b8]">Ver MobOS en acción <ArrowRight size={16}/></a></div><div className="rounded-3xl border border-[#21495c] bg-gradient-to-br from-[#102734] to-[#0b1720] p-7">{['Vendedor ingresa su PIN','Cliente + producto + compatibilidad','Cobro, caja, comisión y garantía'].map((text,i)=><div key={text}><div className="flex items-center gap-4 rounded-2xl border border-white/10 bg-white/5 p-4"><span className="grid h-10 w-10 place-items-center rounded-full bg-[#16d7b8] font-bold text-[#071018]">{i+1}</span><div><b className="block text-sm">{text}</b><small className="text-xs text-slate-400">{i===0?'La venta queda vinculada automáticamente':i===1?'Sugerencias y stock en tiempo real':'Todo conectado sin duplicar trabajo'}</small></div></div>{i<2&&<div className="ml-9 h-8 border-l border-dashed border-[#16d7b8]"/>}</div>)}</div></section>
      <section className="border-y border-white/10 bg-[#0a151e]"><div className="mx-auto grid max-w-6xl gap-12 px-5 py-24 md:grid-cols-2"><div><p className="text-xs font-bold uppercase tracking-[.2em] text-[#16d7b8]">Construido para crecer</p><h2 className="mt-4 text-4xl font-bold tracking-tight">Flexible desde el<br/><span className="text-[#16d7b8]">primer día.</span></h2><p className="mt-5 text-sm leading-7 text-slate-400">Desde una tienda hasta varias empresas y sucursales. Desde un case hasta un equipo con IMEI, garantía y costo de importación.</p></div><div className="grid gap-3 sm:grid-cols-2">{checks.map(check=><div key={check} className="flex gap-3 text-sm text-slate-300"><Check className="mt-0.5 shrink-0 text-[#16d7b8]" size={17}/>{check}</div>)}</div></div></section>
      <section id="precio" className="mx-auto max-w-6xl px-5 py-24"><div className="flex flex-col justify-between gap-10 rounded-3xl bg-gradient-to-br from-[#115c5a] to-[#16d7b8] p-8 text-[#071018] md:flex-row md:items-center md:p-16"><div><p className="text-xs font-bold uppercase tracking-[.2em] text-teal-100">Un plan. Todo incluido.</p><h2 className="mt-4 text-4xl font-bold tracking-tight md:text-5xl">Tu negocio merece<br/>mejor control.</h2><p className="mt-4 max-w-md text-sm leading-6 text-teal-50">POS, inventario, usuarios, pagos, sucursales, reportes, garantías y actualizaciones en un solo plan.</p></div><div className="min-w-[230px]"><div><span className="text-sm font-bold">USD </span><strong className="text-8xl font-bold tracking-[-.08em]">10</strong><span className="text-sm"> / mes</span></div><a href="https://app.controlaria.online" className="mt-5 flex items-center justify-center gap-2 rounded-xl bg-[#071018] px-5 py-3 font-bold text-white">Empezar ahora <ArrowRight size={18}/></a><p className="mt-3 text-center text-xs text-teal-50">Sin permanencia · Soporte incluido</p></div></div></section>
    </main><footer className="mx-auto flex max-w-6xl flex-wrap items-center justify-between gap-5 border-t border-white/10 px-5 py-8 text-xs text-slate-500"><span className="font-semibold text-white">Controlaria · MobOS</span><span>Gestión inteligente para tiendas móviles</span><a href="https://owncoding.dev/" target="_blank" rel="noreferrer" className="font-semibold text-[#16d7b8] hover:underline">Powered by OwnCoding ↗</a></footer>
  </div>
}
