import { useCallback, useEffect, useMemo, useState } from 'react'
import { Activity, ArrowUpRight, CheckCircle2, Clock3, Database, Mail, RefreshCw, ServerCog, ShieldCheck, TriangleAlert, Wifi } from 'lucide-react'
import { APP_CREDIT, APP_CREDIT_URL, APP_VERSION } from '@/lib/brand'
import { checkMobosStatus } from '@/lib/status/checks'
import { publicUrls } from '@/lib/urls'

const definitions = [
  ['app', 'Experiencia MobOS', 'Aplicación web', 'Acceso, POS y panel operativo.', Activity, publicUrls.app],
  ['api', 'Plataforma y datos', 'API MobOS', 'Servicios operativos y autenticación.', ServerCog, `${publicUrls.api}/api/health`],
  ['database', 'Plataforma y datos', 'Base de datos', 'Conexión PostgreSQL confirmada desde el API.', Database],
  ['auth', 'Servicios conectados', 'Acceso con Google', 'Configuración real del proveedor OAuth.', ShieldCheck],
  ['email', 'Servicios conectados', 'Correo de recuperación', 'Proveedor de correo para restablecer contraseñas.', Mail],
  ['reservations', 'Operación', 'Reservas de inventario', 'Protegidas por sesión; se reporta su acceso público real.', Clock3],
  ['cloudflare', 'Infraestructura externa', 'DNS y CDN · Cloudflare', 'Estado publicado por el proveedor.', Wifi, 'https://www.cloudflarestatus.com/', true],
  ['hub', 'Infraestructura externa', 'OwnCoding Hub / Coolify', 'Runtime y despliegues del entorno.', ServerCog, 'https://hub.owncoding.dev/', true],
].map(([id, group, name, detail, icon, href, external]) => ({ id, group, name, detail, icon, href, external }))

const labels = { operational: 'Operativo', checking: 'Verificando', degraded: 'Degradado', restricted: 'Acceso requerido', external: 'Estado externo' }
const styles = { operational: 'bg-[#15D7B8]/10 text-[#40ead0]', checking: 'bg-white/8 text-slate-300', degraded: 'bg-red-400/10 text-red-300', restricted: 'bg-amber-400/10 text-amber-200', external: 'bg-sky-400/10 text-sky-300' }
const dot = { operational: 'bg-[#15D7B8]', checking: 'animate-pulse bg-slate-300', degraded: 'bg-red-400', restricted: 'bg-amber-300', external: 'bg-sky-300' }
const formatTime = (date) => new Intl.DateTimeFormat('es-PY', { dateStyle: 'medium', timeStyle: 'short' }).format(date)

function Badge({ state }) { return <span className={`inline-flex items-center gap-1.5 rounded-full px-2.5 py-1 text-[11px] font-bold ${styles[state] || styles.degraded}`}><i className={`h-1.5 w-1.5 rounded-full ${dot[state] || dot.degraded}`} />{labels[state] || labels.degraded}</span> }

export default function Status() {
  const [report, setReport] = useState({ checkedAt: null, services: {} })
  const [checking, setChecking] = useState(true)
  const check = useCallback(async () => { setChecking(true); try { setReport(await checkMobosStatus()) } catch { setReport({ checkedAt: new Date(), services: {} }) } finally { setChecking(false) } }, [])
  useEffect(() => { check(); const timer = window.setInterval(check, 60_000); return () => window.clearInterval(timer) }, [check])
  const services = useMemo(() => definitions.map(item => ({ ...item, ...(item.external ? { state: 'external', checkDetail: 'Se abre la fuente de estado del proveedor.' } : report.services[item.id] || (checking ? { state: 'checking', detail: 'Esperando la primera comprobación.' } : { state: 'degraded', detail: 'La comprobación no devolvió un resultado.' })) })), [checking, report])
  const degraded = services.some(service => ['degraded', 'restricted'].includes(service.state))
  const groups = ['Experiencia MobOS', 'Plataforma y datos', 'Servicios conectados', 'Operación', 'Infraestructura externa']

  return <main className="min-h-dvh overflow-hidden bg-[#061019] text-white"><div className="pointer-events-none fixed inset-x-0 top-0 h-[26rem] bg-[radial-gradient(ellipse_at_top,rgba(21,215,184,.15),transparent_68%)]" />
    <header className="relative border-b border-white/[.07] bg-[#061019]/75 backdrop-blur-xl"><div className="mx-auto flex max-w-5xl items-center justify-between gap-4 px-5 py-4"><a href={publicUrls.landing} className="flex items-center gap-3"><img src="/logo-dark.svg" alt="MobOS" className="h-8" /><span className="hidden border-l border-white/10 pl-3 text-sm text-slate-400 sm:block">Estado del sistema</span></a><a href={publicUrls.app} className="rounded-xl border border-white/15 px-3.5 py-2 text-sm font-semibold text-[#15D7B8]">Abrir MobOS <ArrowUpRight className="ml-1 inline" size={15} /></a></div></header>
    <section className="relative mx-auto max-w-5xl px-5 pb-10 pt-16 sm:pt-20"><p className="text-xs font-bold uppercase tracking-[.2em] text-[#15D7B8]">Transparencia operativa</p><div className="mt-4 flex flex-col justify-between gap-6 sm:flex-row sm:items-end"><div><h1 className="max-w-2xl text-4xl font-bold tracking-[-.055em] sm:text-6xl">Estado de MobOS</h1><p className="mt-4 max-w-2xl text-base leading-7 text-slate-400">Cada estado proviene de una comprobación actual; no asumimos disponibilidad.</p></div><button onClick={check} className="inline-flex min-h-11 items-center justify-center gap-2 rounded-xl border border-white/15 px-4 text-sm font-semibold text-white hover:border-[#15D7B8]/50"><RefreshCw size={16} className={checking ? 'animate-spin' : ''} />Actualizar</button></div>
      <div className={`mt-10 rounded-3xl border p-6 sm:p-8 ${degraded ? 'border-amber-400/30 bg-amber-400/[.07]' : 'border-[#15D7B8]/25 bg-[#15D7B8]/[.07]'}`}><div className="flex gap-4"><span className={`grid h-11 w-11 shrink-0 place-items-center rounded-2xl ${degraded ? 'bg-amber-400/15 text-amber-200' : 'bg-[#15D7B8]/15 text-[#15D7B8]'}`}>{degraded ? <TriangleAlert size={22} /> : <CheckCircle2 size={22} />}</span><div><h2 className="text-lg font-bold">{checking ? 'Verificando servicios' : degraded ? 'Operación parcialmente degradada' : 'Los servicios comprobables están operativos'}</h2><p className="mt-1 text-sm leading-6 text-slate-300">{degraded ? 'Algún servicio no confirmó disponibilidad o requiere una sesión autenticada. Revisá el detalle antes de operar.' : 'Los proveedores externos conservan su propio estado y no cuentan como verificación de MobOS.'}</p></div></div></div></section>
    <section className="relative mx-auto max-w-5xl px-5 pb-16">{groups.map(group => <div key={group} className="mb-8"><h2 className="mb-3 text-xs font-bold uppercase tracking-[.18em] text-slate-500">{group}</h2><div className="overflow-hidden rounded-2xl border border-white/[.09] bg-[#0a1923]">{services.filter(item => item.group === group).map((service, index, list) => { const Icon = service.icon; return <div key={service.id} className={`flex flex-col gap-4 px-5 py-5 sm:flex-row sm:items-center sm:justify-between ${index < list.length - 1 ? 'border-b border-white/[.07]' : ''}`}><div className="flex min-w-0 items-start gap-3"><span className="grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-white/[.055] text-[#15D7B8]"><Icon size={19} /></span><div><h3 className="text-sm font-bold">{service.name}</h3><p className="mt-1 text-sm text-slate-400">{service.detail}</p><p className="mt-1 text-xs text-slate-500">{service.checkDetail || service.detail}</p></div></div><div className="flex shrink-0 items-center gap-3"><Badge state={service.state} />{service.href && <a href={service.href} target="_blank" rel="noreferrer" aria-label={`Abrir ${service.name}`} className="rounded-lg p-2 text-slate-400 hover:bg-white/5 hover:text-[#15D7B8]"><ArrowUpRight size={17} /></a>}</div></div> })}</div></div>)}
      <div className="mt-10 grid gap-4 rounded-2xl border border-white/[.09] bg-white/[.025] p-5 sm:grid-cols-[1fr_auto] sm:items-center"><div className="flex gap-3"><Clock3 className="mt-0.5 shrink-0 text-[#15D7B8]" size={18} /><div><h2 className="text-sm font-bold">Última comprobación</h2><p className="mt-1 text-sm text-slate-400">{report.checkedAt ? formatTime(report.checkedAt) : 'Esperando respuesta…'} · Actualización automática cada minuto.</p></div></div><span className="text-xs text-slate-500">No se muestran datos de clientes ni tiendas.</span></div></section>
    <footer className="relative border-t border-white/[.07] px-5 py-8"><div className="mx-auto flex max-w-5xl flex-wrap items-center justify-between gap-4 text-xs text-slate-500"><span>MobOS · Estado del sistema · {APP_VERSION}</span><a href={APP_CREDIT_URL} target="_blank" rel="noreferrer" className="font-semibold text-[#15D7B8] hover:underline">{APP_CREDIT}</a></div></footer></main>
}
