import { useEffect, useMemo, useState } from 'react'
import { Card, Button, Input, Label, Textarea, Badge } from '@/components/ui'
import Icon from '@/components/shared/Icon'
import { api } from '@/lib/api'
import { useSesion } from '@/lib/sesion'
import { getDemoWarranties, saveDemoWarranties } from '@/lib/demoWarranties'

const STATES = [['RECEIVED', 'Recibido'], ['DIAGNOSIS', 'En diagnóstico'], ['READY', 'Listo'], ['DELIVERED', 'Entregado']]
const label = Object.fromEntries(STATES)
const blank = { customerName: '', serial: '', description: '', responsibleName: '', technicianName: '', diagnosis: '', partsText: '', photosText: '', branchId: '' }

export default function Garantias() {
  const { esDemo, sucursal } = useSesion()
  const [items, setItems] = useState([]); const [q, setQ] = useState(''); const [form, setForm] = useState(blank); const [error, setError] = useState(''); const [saving, setSaving] = useState(false); const [advancingId, setAdvancingId] = useState(null)
  async function load() { try { setItems(esDemo ? getDemoWarranties() : await api.get(`/api/warranties?q=${encodeURIComponent(q)}`)) } catch (e) { setError(e.message) } }
  useEffect(() => { load() }, [esDemo])
  const visible = useMemo(() => esDemo ? items.filter((x) => [x.customerName, x.serial, x.description].some((v) => v.toLowerCase().includes(q.toLowerCase()))) : items, [items, q, esDemo])
  const listInput = (value) => value.split('\n').map((item) => item.trim()).filter(Boolean)
  async function create(e) { e.preventDefault(); setSaving(true); setError(''); try { const { partsText, photosText, ...base } = form; const data = { ...base, parts: listInput(partsText), photos: listInput(photosText), branchId: form.branchId || sucursal?.id }; if (esDemo) setItems(saveDemoWarranties([{ ...data, id: `demo-${Date.now()}`, status: 'RECEIVED', createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() }, ...items])); else setItems([await api.post('/api/warranties', data), ...items]); setForm(blank) } catch (e) { setError(e.message) } finally { setSaving(false) } }
  async function advance(item) { const next = STATES[STATES.findIndex(([s]) => s === item.status) + 1]?.[0]; if (!next || advancingId) return; setAdvancingId(item.id); setError(''); try { if (esDemo) { const nextItems = items.map((x) => x.id === item.id ? { ...x, status: next, updatedAt: new Date().toISOString() } : x); setItems(saveDemoWarranties(nextItems)) } else { const updated = await api.patch('/api/warranties', { id: item.id, status: next }); setItems(items.map((x) => x.id === item.id ? updated : x)) } } catch (e) { setError(e.message) } finally { setAdvancingId(null) } }
  return <div className="space-y-5"><div className="flex flex-wrap items-end justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-fono-light">Servicio y seguimiento</p><h2 className="mt-1 text-2xl font-bold tracking-tight">Garantías</h2><p className="mt-1 text-sm text-mute">Seguimiento por caso, sin inventar cobertura automática.</p></div><div className="relative w-full max-w-sm"><Icon name="search" className="pointer-events-none absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-mute" /><Input value={q} onChange={(e) => setQ(e.target.value)} onKeyDown={(e) => e.key === 'Enter' && load()} placeholder="Buscar cliente, serial o detalle…" className="pl-9" aria-label="Buscar garantías" /></div></div>
    <Card><form onSubmit={create} className="grid gap-3 md:grid-cols-2"><div><Label>Cliente</Label><Input required value={form.customerName} onChange={(e) => setForm({ ...form, customerName: e.target.value })} placeholder="Nombre del cliente" /></div><div><Label>Serial / IMEI</Label><Input required value={form.serial} onChange={(e) => setForm({ ...form, serial: e.target.value })} placeholder="Serial o IMEI" /></div><div className="md:col-span-2"><Label>Descripción del caso</Label><Textarea required rows={2} value={form.description} onChange={(e) => setForm({ ...form, description: e.target.value })} placeholder="Falla reportada, revisión solicitada…" /></div><div><Label>Responsable</Label><Input value={form.responsibleName} onChange={(e) => setForm({ ...form, responsibleName: e.target.value })} placeholder="Persona responsable" /></div><div><Label>Técnico asignado</Label><Input value={form.technicianName} onChange={(e) => setForm({ ...form, technicianName: e.target.value })} placeholder="Técnico responsable" /></div><div className="md:col-span-2"><Label>Diagnóstico inicial</Label><Textarea rows={2} value={form.diagnosis} onChange={(e) => setForm({ ...form, diagnosis: e.target.value })} placeholder="Pruebas, causa probable y condición de recepción…" /></div><div><Label>Repuestos (uno por línea)</Label><Textarea rows={2} value={form.partsText} onChange={(e) => setForm({ ...form, partsText: e.target.value })} placeholder="Pantalla OLED\nBatería" /></div><div><Label>Fotos / enlaces (uno por línea)</Label><Textarea rows={2} value={form.photosText} onChange={(e) => setForm({ ...form, photosText: e.target.value })} placeholder="https://…" /></div><Button type="submit" disabled={saving} className="md:col-span-2 min-h-11">{saving ? 'Guardando…' : 'Registrar caso'}</Button></form></Card>
    {error && <p role="alert" className="rounded-xl border border-bad/30 bg-bad/10 px-4 py-3 text-sm text-bad">{error}</p>}
    <div className="grid gap-3 md:grid-cols-2 xl:grid-cols-4">{visible.map((item) => <Card key={item.id} className="border-fono/20"><div className="flex items-start justify-between gap-3"><div className="min-w-0"><p className="truncate font-semibold">{item.customerName}</p><p className="mt-1 text-xs font-mono text-fono-light">{item.serial}</p></div><Badge color={item.status === 'DELIVERED' ? 'green' : item.status === 'READY' ? 'orange' : 'slate'}>{label[item.status]}</Badge></div><p className="mt-4 min-h-12 text-sm leading-6 text-mute">{item.description}</p>{item.diagnosis && <p className="mt-2 rounded-lg bg-ink-700 p-2 text-xs text-mute">Diagnóstico: {item.diagnosis}</p>}<div className="mt-3 space-y-1 text-xs text-mute"><p>Técnico: {item.technicianName || 'Sin asignar'}</p>{item.parts?.length > 0 && <p>Repuestos: {item.parts.join(', ')}</p>}{item.photos?.length > 0 && <p>{item.photos.length} foto(s) o enlace(s) adjuntos</p>}</div><div className="mt-4 flex items-center justify-between gap-2 border-t border-ink-600 pt-3 text-xs text-mute"><span>{item.responsibleName || 'Sin responsable'}</span>{item.status !== 'DELIVERED' && <Button type="button" variant="outline" disabled={advancingId !== null} className="h-8 px-2 text-xs" onClick={() => advance(item)}>{advancingId === item.id ? 'Actualizando…' : 'Avanzar'}</Button>}</div></Card>)}</div>{!visible.length && <Card className="py-12 text-center text-sm text-mute">No hay casos que coincidan con la búsqueda.</Card>}</div>
}
